### ISSUE TITLE
Suggestions from User

### ISSUE THREAD

**Issue by dimoschi** [transifex/transifex-sync-zendesk#41]
* a search function so it's easier to track down certain articles, sections and categories
* a column that contains the article, section or category title
* also it would be nice if it's possible to extend the amount of rows that are shown (no it's 7)

**Comment by matthewjackowski** [comment]
I think these are all covered in other issues.  Closing multiple request tickets.  If there is a specific one that needs to be addressed...please create a new issue with it.
