### ISSUE TITLE
Changing the resource name in Transifex breaks Sync-ing

### ISSUE THREAD

**Issue by matthewjackowski** [transifex/transifex-sync-zendesk#42]
Zendesk Sync uses the name of the resource to maintain a relationship between Zendesk and Transifex.  Unfortunately both name and slug can be changed...the app should at least be smart enough to know that it is missing a proper name in one or both.  And signal the user appropiately.

**Comment by SofiaMargariti** [comment]
In new UI if a resource slug changes the users will see `No resource yet` and they will have to go back in transifex and update the slug. I don't think there is much more we can do about this. @samuelchan22 can I close this?
