### ISSUE TITLE
Suggestion from Users #2

### ISSUE THREAD

**Issue by dimoschi** [transifex/transifex-sync-zendesk#44]
Here are more suggestions:
* And 'order by' options for articles (such as name, date, etc) would make going through pages easier
* Filters for articles/sections/categories that have not been uploaded or downloaded
* You cannot tell which page is currently selected when using the navigation controls
* Addition of an 'upload all' button
* Addition of a 'download all' button
* Last uploaded field
* Upload button when pressed after a previous upload, there is no way to tell if the upload command was initiated correctly

@matthewjackowski I don't know if you want me to keep all the feedback in one issue that will be updated, or you prefer to create a new one.

**Comment by matthewjackowski** [comment]
@dimoschi we should break these up at some point.  But they can be left like this for now.

**Comment by matthewjackowski** [comment]
I think these are all covered in other issues.  Closing multiple request tickets.  If there is a specific one that needs to be addressed...please create a new issue with it.
