### ISSUE TITLE
Segment HTML blobs into native strings

### ISSUE THREAD

**Issue by matthewjackowski** [transifex/transifex-sync-zendesk#45]
Currently the sync tool pushes the entire html blob into the source...this is undesirable for building TM.  Instead if the html can be optionally segmented this would allow translations to be maintained in a more natural way.

**Comment by dimoschi** [comment]
@matthewjackowski Can you please prioritize this, since it's impossible for the translators to work on huge strings.

**Comment by matthewjackowski** [comment]
@dimoschi Reopened and reassigned.

**Comment by samuelchan22** [comment]
Done for the next release.
