### ISSUE TITLE
Show more articles per page

### ISSUE THREAD

**Issue by matthewjackowski** [transifex/transifex-sync-zendesk#54]
Another solution would be to give the choice in your Zendesk app to show more articles per page. Right now we have 72 pages to go through and use the browser's Find feature. I I could see 100 articles at a time, this process of finding a specific one round be very quick.

**Comment by charlesangelis** [comment]
I would like to elaborate a bit on the challenge of using Transfex with the Zendesk integration.  We have nearly 500 support articles that need translation. The integration in Zendesk allows us to see 7 articles at a time. As we update our articles and create new ones, using the current functionality, I will have to go page-by-page (7 articles at a time) until I find the ones that don't have the "Download" button lit up in green, and upload them to Transfex.  Using the browser's search is even slower with all the keystrokes, as I can only search one page at a time, 7 articles at a time.  What would greatly help here is the ability to:

1. The option to view more articles on a single page load (such as 25, 50, 100)

2. A built-in search function to search by article # or title

3. The option to sort by articles not uploaded, changed, etc

**Comment by SofiaMargariti** [comment]
fixed in version 2.0
