### ISSUE TITLE
Buttons for content type not switching

### ISSUE THREAD

**Issue by matthewjackowski** [transifex/transifex-sync-zendesk#63]
Looks like buttons are here:
https://github.com/transifex/transifex-sync-zendesk/blob/master/src/templates/sync_page_articles.hdbs#L10

but the "page action" is missing from the UI functions:
https://github.com/transifex/transifex-sync-zendesk/blob/master/src/lib/ui/sync-articles.js#L32

So all that should be needed is a handler function that does:
```
this.switchTo('sync_categories');
```

**Comment by matthewjackowski** [comment]
@nbasili @SofiaMargariti per our conversation

**Comment by SofiaMargariti** [comment]
fixed in 2.0
